name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
          
      - name: Install dependencies
        run: |
          cd backend
          npm ci
          
      - name: Create environment file
        run: |
          cd backend
          echo "PORT=${{ secrets.PORT || '5000' }}" > .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}" >> .env
          echo "RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}" >> .env
          
      # Add your deployment steps here (e.g., deploy to Heroku, Railway, etc.)
      # Example for Railway:
      # - name: Deploy to Railway
      #   uses: railway-app/railway@v1
      #   with:
      #     token: ${{ secrets.RAILWAY_TOKEN }}
      #     service: your-service-name
